source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'QonversionSandwich' do
  pod 'Qonversion', '3.4.1'
end

target 'Sample' do
  pod 'QonversionSandwich', :path => '../'
end
