source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

target 'Sample' do
  pod 'QonversionSandwich', :path => '../'
  pod 'Qonversion', :git => 'https://github.com/qonversion/qonversion-ios-sdk.git', :branch => 'feature/deferred-purchase-listener'
end
